smth

diff --git a/mole b/mole
--- a/mole
+++ b/mole
@@ -38,7 +38,7 @@ open_file_from_dir() {
 
     if [ "$filename" = "/" ]
     then
-        echo "No entries that meets your filters" 1>&2
+        echo "No entries that match your filters" 1>&2
         exit 3
     fi
 }
@@ -46,6 +46,40 @@ check_args_correctness() {
     if [ "$1" = "file" ]
     then
         if [ "$2" != "" ] || [ "$3" != "" ] || [ "$4" != "" ]
+        then
+            echo "Invalid options selected. Use -h for help." 1>&2
+            exit 1
+        fi
+    elif [ "$1" = "dir" ]
+    then
+        if [ "$2" != "true" ] && [ "$2" != "" ]
+        then
+            echo "Coder's problem." 1>&2
+            exit 1
+        fi
+        if [ "$(echo "$3" | grep -E -m 1 "[0-9]{4}-[0-9]{2}-[0-9]{2}")" = "" ] && [ "$3" != "" ]
+        then
+            echo "Invalid options selected. Use -h for help." 1>&2
+            exit 1
+        fi
+        if [ "$(echo "$4" | grep -E -m 1 "[0-9]{4}-[0-9]{2}-[0-9]{2}")" = "" ] && [ "$4" != "" ]
+        then
+            echo "Invalid options selected. Use -h for help." 1>&2
+            exit 1
+        fi
+    elif [ "$1" = "list" ] || [ "$1" = "secret-log" ]
+    then
+        if [ "$2" != "" ]
+        then
+            echo "Invalid options selected. Use -h for help." 1>&2
+            exit 1
+        fi
+        if [ "$(echo "$3" | grep -E -m 1 "[0-9]{4}-[0-9]{2}-[0-9]{2}")" = "" ] && [ "$3" != "" ]
+        then
+            echo "Invalid options selected. Use -h for help." 1>&2
+            exit 1
+        fi
+        if [ "$(echo "$4" | grep -E -m 1 "[0-9]{4}-[0-9]{2}-[0-9]{2}")" = "" ] && [ "$4" != "" ]
         then
             echo "Invalid options selected. Use -h for help." 1>&2
             exit 1
@@ -58,10 +92,19 @@ check_env_variables() {
         echo "MOLE_RC not set"
         exit 2
     fi
-
+    if [ "$EDITOR" = "" ]
+    then
+        if [ "$VISUAL" = "" ]
+        then
+            editor='vi'
+        else
+            editor="$VISUAL"
+        fi
+    else
+        editor="$EDITOR"
+    fi
 }
 make_list() {
-    # awk -v file="$1" 'BEGIN{FS=OFS=";"} {if ($1==file) {print $0}}' "$MOLE_RC" | awk 'BEGIN{FS=OFS=";"; maxlength=0} {if (maxlength < length($2)) {maxlength = length($2);}} END{print maxlength+1}'
     check_env_variables
     shift 1
     while getopts ":g:a:b:" argum; do
@@ -83,6 +126,8 @@ make_list() {
     done
     shift "$((OPTIND-1))"
 
+    check_args_correctness "list" "$recentlyflag" "$afterdate" "$beforedate"
+
     if [ "$1" = "" ]
     then
         filename="$(pwd)"
@@ -96,8 +141,59 @@ make_list() {
         exit 3
     fi
 
-    sort "$MOLE_RC" | awk -v file="$filename" -v groupsstr="$groups" 'BEGIN{FS=OFS=";"; if (groupsstr != "") {groupsnum=split(groupsstr, groups, ",");}} {if (groupsstr != "") {for (i in groups) {kek=$3; if ($1==file && gsub(groups[i]",", "rep", kek) != 0) {print $0}}} else {if ($1==file) {print $0}}}' | awk -v afterdate="$afterdate" -v beforedate="$beforedate" 'BEGIN{FS=OFS=";"; if (afterdate=="") {afterdate="1901-12-14"}; if (beforedate=="") {beforedate="9999-01-01"};} {for (i=4; i<NF+1; i+=1) {split($i, datearr, "_"); if (datearr[1] < beforedate && datearr[1] > afterdate) {print $0; next;}}}' | awk 'BEGIN{FS=OFS=";";} {print $2":;"substr($3, 1, length($3)-1);}' | column -t -s ";" -c 1
+    sort "$MOLE_RC" | awk -v file="$filename" -v groupsstr="$groups" 'BEGIN{FS=OFS=";"; if (groupsstr != "") {groupsnum=split(groupsstr, groups, ",");}} {if (groupsstr != "") {for (i in groups) {kek=$3; if ($1==file && gsub(groups[i]",", "rep", kek) != 0) {print $0}}} else {if ($1==file) {print $0}}}' | awk -v afterdate="$afterdate" -v beforedate="$beforedate" 'BEGIN{FS=OFS=";"; if (afterdate=="") {afterdate="1901-12-14"}; if (beforedate=="") {beforedate="9999-01-01"};} {for (i=4; i<NF+1; i+=1) {split($i, datearr, "_"); if (datearr[1] < beforedate && datearr[1] > afterdate) {print $0; next;}}}' | awk 'BEGIN{FS=OFS=";";} {if ($3 == "") {print $2":;-";} else {print $2":;"substr($3, 1, length($3)-1);}}' | column -t -s ";"
 
+}
+make_secret_log() {
+    check_env_variables
+    shift 1
+    while getopts ":g:a:b:" argum; do
+        case "${argum}" in
+            g)
+                groups="${OPTARG}"
+                ;;
+            a)
+                afterdate="${OPTARG}"
+                ;;
+            b)
+                beforedate="${OPTARG}"
+                ;;
+            *)
+                echo "Invalid options selected. Use -h for help." 1>&2
+                exit 1
+                ;;
+        esac
+    done
+    shift "$((OPTIND-1))"
+
+    check_args_correctness "secret-log" "$recentlyflag" "$afterdate" "$beforedate"
+
+    if [ "$1" = "" ]
+    then
+        awk -v afterdate="$afterdate" -v beforedate="$beforedate" 'BEGIN{FS=OFS=";"; if (afterdate=="") {afterdate="1901-12-14"}; if (beforedate=="") {beforedate="9999-01-01"};} {result = ""; for (i=4; i<NF+1; i+=1) {split($i, datearr, "_"); if (datearr[1] < beforedate && datearr[1] > afterdate) {if (result == "") {result = $1"/"$2";"$(i)} else {result = result";"$(i)}}} if (result != "") {print result;}}' "$MOLE_RC"
+        exit 0
+    fi
+
+    for i in "$@"
+    do
+        filename="$(realpath -s "$i")"
+        if [ "$(find "$filename" -type d -maxdepth 0 -exec echo dir \; 2>/dev/null)" != "dir" ]
+        then
+            echo "mole secret_log needs folder as argument!" 1>&2
+            exit 3
+        fi
+        awk -v file="$filename" 'BEGIN{FS=OFS=";"} {if ($1==file) {print $0}}' "$MOLE_RC" | awk -v afterdate="$afterdate" -v beforedate="$beforedate" 'BEGIN{FS=OFS=";"; if (afterdate=="") {afterdate="1901-12-14"}; if (beforedate=="") {beforedate="9999-01-01"};} {result = ""; for (i=4; i<NF+1; i+=1) {split($i, datearr, "_"); if (datearr[1] < beforedate && datearr[1] > afterdate) {if (result == "") {result = $1"/"$2";"$(i)} else {result = result";"$(i)}}} if (result != "") {print result;}}'
+    done
+
+    if [ "$(find "$filename" -type d -maxdepth 0 -exec echo dir \; 2>/dev/null)" != "dir" ]
+    then
+        echo "mole list needs folder as argument!" 1>&2
+        exit 3
+    fi
+
+    # awk -v file="$filename" 'BEGIN{FS=OFS=";"; filesnum=split(filename, fileslist, " ")} {for (i in fileslist) {if ($1==fileslist[i]) {print $0}}}' "$MOLE_RC"
+
+    # awk -v file="$filename" 'BEGIN{FS=OFS=";"; filesnum=split(filename, fileslist, " ")} {if ($1==fileslist[i]) {print $0}}' "$MOLE_RC" | awk -v afterdate="$afterdate" -v beforedate="$beforedate" 'BEGIN{FS=OFS=";"; if (afterdate=="") {afterdate="1901-12-14"}; if (beforedate=="") {beforedate="9999-01-01"};} {result = ""; for (i=4; i<NF+1; i+=1) {split($i, datearr, "_"); if (datearr[1] < beforedate && datearr[1] > afterdate) {if (result == "") {result = $1"/"$2";"$(i)} else {result = result";"$(i)}}} if (result != "") {print result;}}'
 }
 
 
@@ -106,6 +202,12 @@ check_env_variables
 if [ "$1" = "list" ]
 then
     make_list "$@"
+    exit 0
+fi
+
+if [ "$1" = "secret-log" ]
+then
+    make_secret_log "$@"
     exit 0
 fi
 
@@ -121,7 +223,7 @@ while getopts ":hmg:a:b:" argum; do
             recentlyflag="true"
             ;;
         a)
-            afterdate="${OPTARG}"
+            afterdate="${OPTARG}" # [0-9]{4}-[0-9]{2}-[0-9]{2}
             ;;
         b)
             beforedate="${OPTARG}"
@@ -149,7 +251,7 @@ then
     filepath="$(echo "$filename" | rev | cut -d'/' -f 2- | rev)"
     onlyfilename="$(echo "$filename" | rev | cut -d'/' -f 1 | rev)"
     write_a_record "$filepath" "$onlyfilename" "$groups" "$(date "+%Y-%m-%d_%H-%M-%S")"
-    vim "$filename"
+    eval "$editor $filename"
 else
     check_args_correctness "dir" "$recentlyflag" "$afterdate" "$beforedate"
     if [ "$recentlyflag" != "" ]
@@ -158,12 +260,12 @@ else
         filepath="$(echo "$filename" | rev | cut -d'/' -f 2- | rev)"
         onlyfilename="$(echo "$filename" | rev | cut -d'/' -f 1 | rev)"
         write_a_record "$filepath" "$onlyfilename" "$groups" "$(date "+%Y-%m-%d_%H-%M-%S")"
-        vim "$filename"
+        eval "$editor $filename"
     else
         open_file_from_dir "recently" "$filename" "$groups" "$afterdate" "$beforedate"
         filepath="$(echo "$filename" | rev | cut -d'/' -f 2- | rev)"
         onlyfilename="$(echo "$filename" | rev | cut -d'/' -f 1 | rev)"
         write_a_record "$filepath" "$onlyfilename" "$groups" "$(date "+%Y-%m-%d_%H-%M-%S")"
-        vim "$filename"
+        eval "$editor $filename"
     fi
 fi
